# Class definition

In [ ]:
class DecisionTree:
    """
    Decision Tree is a non-parametric supervised learning method. It is a model that predicts
    the value of a target variable by learning simple decision rules inferred from the features. 
    It can be seen as a piecewise constant approximation.

    Needed packages:
    import numpy as np

    Parameters
    ----------
    fit_intercept : bool, default = True,
        Specifies if a constant should be added to the regression.
    
    batch_size : int, default = 1000
        Size of the batch in SGD loop.
    
    no_epochs : int, default = 10000
        Number of epochs taken for the SGD to converge.
        
    learning_rate : float, default = 0.01
        Learning rate in SGD.
    
    tolerance : float, default = 1e-10
        Tolerance for stopping criteria.
    
    verbose : bool, default = False
        Boolean to print or suppress epochs in SGD loop.
        
        
    Attributes
    ----------
    n_features : int
        Number of features seen during method `fit`, excluding intercept.
        
    classes_ : ndarray of shape n_classes
        A list of class labels seen during method `fit`.
    
    n_classes : int
        Number of target classes seen during method `fit`.

    
    Methods
    ----------
    fit(X,y):
        Fit Logistic regression model.
        
    predict(X, boundary=0.5):
        Predict using the fitted parameters of this Logistic Regression estimator.
        
    predict_prob(X, boundary=0.5):
        Predict probability using the fitted parameters of this Logistic Regression estimator.
        
    accuracy(y, y_pred)
        Print accuracy of fitted Logistic Regression estimator
    
        
    Examples
    --------
    >>> import numpy as np
    >>> X = np.array([[-1, 1], [1, 2], [3, 4], [-3, 1], [-1, 0]])
    >>> y = np.array([1, 0, 1, 0, 0])

    >>> regfit = LogisticRegression(verbose=False, no_epochs=100000, tolerance=1e-10, fit_intercept=True).fit(X,y)
    >>> regfit.n_features
    2
    >>> regfit.classes
    array([0, 1])
    >>> regfit.n_classes
    2
    >>> regfit.coefficients
    array([[-1.93422523],
           [ 0.04175192],
           [ 0.93863707]])
    >>> regfit.intercept
    array([-1.93422523])
    >>> regfit.residuals
    array([[-0.73833641],
           [ 0.49620032],
           [-0.12503628],
           [ 0.24585473],
           [ 0.1217484 ]])
    >>> regfit.deviance_residuals
    array([[-1.63749542],
           [ 1.17096248],
           [-0.5168614 ],
           [ 0.75122601],
           [ 0.50955307]])
    >>> regfit.predict(X)
    array([0, 0, 1, 0, 0])
    >>> regfit.predict_prob(X)
    array([[0.73833645, 0.26166355],
           [0.50379972, 0.49620028],
           [0.12503625, 0.87496375],
           [0.75414522, 0.24585478],
           [0.87825167, 0.12174833]])
    >>> regfit.accuracy(y, regfit.y_pred)
    0.8
    """
    
    def __init__(
        self,
        fit_intercept = True,
        batch_size = 1000, 
        no_epochs = 10000, 
        learning_rate = 0.01,
        tolerance = 1e-10,
        verbose = False,
    ):
        self.fit_intercept = fit_intercept
        self.batch_size = batch_size
        self.no_epochs = no_epochs
        self.learning_rate = learning_rate
        self.tolerance = tolerance
        self.verbose = verbose
        
    @staticmethod
    def gini_impurity(z):
        p = np.unique(z, return_counts=True)[1]/y.shape[0]
        gini = 1 - np.sum(p**2)
        return gini
    
    @staticmethod
    def entropy(z):
        a = np.unique(z, return_counts=True)[1]/z.shape[0]
        entropy = np.sum(-a * np.log2(a + 1e-99))
        return entropy
        
    def fit(self, X, y):
        """
        Fit Logistic regression model.

        Parameters
        ----------
        X : array of shape Nxk (Training data)
        y : array of shape N (Target values)

        Returns
        -------
        self : object
            Fitted Estimator.
        """
        # Define number of features and classes
        self.n_features = len(X[0])
        self.classes = np.unique(y)
        self.n_classes = len(self.classes)
        
        return self
        
       
    def predict(self, X, boundary=0.5):
        """
        Predict target using the fitted parameters of this Logistic Regression estimator.

        Parameters
        ----------
        X : array of shape M, k-1
            Values for regressors test data. (Don't add 1 for the intercept)

        Returns
        -------
        C : array of shape M
            Returns predicted values.
        """
        
        if hasattr(self, 'coefficients') == False:
                raise ValueError(
                     " This LogisticRegression instance is not fitted yet." \
                     " Call 'fit' method with appropriate X and y before using this predict function."
                 )
        
        
        return self.y_pred
    
    def predict_prob(self, X, boundary=0.5):
        """
        Predict probability using the fitted parameters of this Logistic Regression estimator.

        Parameters
        ----------
        X : array of shape M, k-1
            Values for regressors test data. (Don't add 1 for the intercept)
            
        boundary : float
            Value of decision boundary. If estimated probability > boundary, predict 1.

        Returns
        -------
        C : array of shape M
            Returns predicted values.
        """
        
        if hasattr(self, 'coefficients') == False:
                raise ValueError(
                     " This LogisticRegression instance is not fitted yet." \
                     " Call 'fit' method with appropriate X and y before using this predict function."
                 )
        
        self.predict(X)
        
        probs = np.append(1-self.y_hat, self.y_hat, axis=1)
        
        return probs
    
    def accuracy(self, X_test, y_test):
        """
        Print accuracy of fitted Decision Tree estimator.

        Parameters
        ----------
        y : array of shape N
            Values for true test data.

        Returns
        -------
        C : constant
            Returns accuracy.
        """
        
        if hasattr(self, 'coefficients') == False:
                raise ValueError(
                     " This LogisticRegression instance is not fitted yet." \
                     " Call 'fit' method with appropriate X and y before using this predict function."
                 )
                
        ## ...
        ## ...
        
        return self

## Examples

In [ ]:
import numpy as np
import pandas as pd
X = np.array([[-1, 1], [1, 2], [3, 4], [-3, 1], [-1, 0]])
y = np.array([1, 0, 1, 0, 0])



In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)

In [ ]:
def gini_impurity(z):
    p = np.unique(z, return_counts=True)[1]/z.shape[0]
    gini = 1 - np.sum(p**2)
    return gini

def entropy(z):
    a = np.unique(z, return_counts=True)[1]/z.shape[0]
    entropy = np.sum(-a * np.log2(a + 1e-99))
    return entropy

def information_gain(y, split, func=entropy):
    '''
    Returns the Information Gain of a variable given a loss function.
    y : 
        Target variable.
    split: 
        Split choice.
    func: 
        Function to be used to calculate Information Gain in case os classification.
    '''
    a = sum(split)
    b = split.shape[0] - a
    
    if(a == 0 or b ==0): 
        ig = 0

    else:
        if y.dtypes != 'O':
            ig = y.var() - (a/(a+b)* y[split].var()) - (b/(a+b)*y[-split].var())
        else:
            ig = func(y)-a/(a+b)*func(y[split])-b/(a+b)*func(y[-split])

    return ig

In [ ]:
values = [['Male',174,96,4], 
          ['Male',189,87,2], 
          ['Female',185,110,4],
          ['Female',195,104,3],
          ['Male',149,61,3]]

y = pd.DataFrame(values, columns = ['Gender' , 'Height' , 'Weight'  ,'Index'])

y['obese'] = (y.Index >= 4).astype('int')
y.drop('Index', axis = 1, inplace = True)

y

In [ ]:
information_gain(y['obese'], y['Gender'] == 'Male')

In [13]:
import pandas as pd
import numpy as np

data = pd.read_csv("500data2.csv")
data['obese'] = (data.Index >= 4).astype('int')
data.drop('Index', axis = 1, inplace = True)

print(
  " Misclassified when cutting at 100kg:",
  data.loc[(data['Weight']>=100) & (data['obese']==0),:].shape[0], "\n",
  "Misclassified when cutting at 80kg:",
  data.loc[(data['Weight']>=80) & (data['obese']==0),:].shape[0]
)

 Misclassified when cutting at 100kg: 18 
 Misclassified when cutting at 80kg: 63


In [14]:
def gini_impurity(y):
  '''
  Given a Pandas Series, it calculates the Gini Impurity. 
  y: variable with which calculate Gini Impurity.
  '''
  if isinstance(y, pd.Series):
    p = y.value_counts()/y.shape[0]
    gini = 1-np.sum(p**2)
    return(gini)

  else:
    raise('Object must be a Pandas Series.')

gini_impurity(data.Gender)

0.4998

In [15]:
def entropy(y):
  '''
  Given a Pandas Series, it calculates the entropy. 
  y: variable with which calculate entropy.
  '''
  if isinstance(y, pd.Series):
    a = y.value_counts()/y.shape[0]
    entropy = np.sum(-a*np.log2(a+1e-9))
    return(entropy)

  else:
    raise('Object must be a Pandas Series.')

entropy(data.Gender)

0.9997114388674198

In [16]:
def variance(y):
  '''
  Function to help calculate the variance avoiding nan.
  y: variable to calculate variance to. It should be a Pandas Series.
  '''
  if(len(y) == 1):
    return 0
  else:
    return y.var()

def information_gain(y, mask, func=entropy):
    '''
      It returns the Information Gain of a variable given a loss function.
      y: target variable.
      mask: split choice.
      func: function to be used to calculate Information Gain in case os classification.
    '''
    a = sum(mask)
    b = mask.shape[0] - a
    
    if(a == 0 or b ==0): ig = 0
    else:
        if y.dtypes != 'O':
            ig = variance(y) - (a/(a+b)* variance(y[mask])) - (b/(a+b)*variance(y[-mask]))
        else:
            ig = func(y)-a/(a+b)*func(y[mask])-b/(a+b)*func(y[-mask])
    
    return ig

information_gain(data['obese'], data['Gender'] == 'Male')

-0.0002808244603327431

In [17]:
import itertools

def categorical_options(a):
    '''
    Creates all possible combinations from a Pandas Series.
    a: Pandas Series from where to get all possible combinations. 
    '''
    a = a.unique()

    opciones = []
    
    for L in range(0, len(a)+1):
        for subset in itertools.combinations(a, L):
            subset = list(subset)
            opciones.append(subset)

    return opciones[1:-1]

def max_information_gain_split(x, y, func=entropy):
    '''
    Given a predictor & target variable, returns the best split, the error and the type of variable based on a selected cost function.
    x: predictor variable as Pandas Series.
    y: target variable as Pandas Series.
    func: function to be used to calculate the best split.
    '''

    split_value = []
    ig = [] 

    numeric_variable = True if x.dtypes != 'O' else False

    # Create options according to variable type
    if numeric_variable:
        options = x.sort_values().unique()[1:]
    else: 
        options = categorical_options(x)

    # Calculate ig for all values
    for val in options:
        mask =   x < val if numeric_variable else x.isin(val)
        val_ig = information_gain(y, mask, func)
        # Append results
        ig.append(val_ig)
        split_value.append(val)

    # Check if there are more than 1 results if not, return False
    if len(ig) == 0:
        return(None,None,None, False)

    else:
        # Get results with highest IG
        best_ig = max(ig)
        best_ig_index = ig.index(best_ig)
        best_split = split_value[best_ig_index]
        
        return(best_ig,best_split,numeric_variable, True)


weight_ig, weight_slpit, _, _ = max_information_gain_split(data['Weight'], data['obese'],)  


print(
  "The best split for Weight is when the variable is less than ",
  weight_slpit,"\nInformation Gain for that split is:", weight_ig
)

The best split for Weight is when the variable is less than  103 
Information Gain for that split is: 0.10625190497954848


In [18]:
data.drop('obese', axis= 1).apply(max_information_gain_split, y = data['obese'])

Gender    Height    Weight
0 -0.000281  0.019684  0.106252
1    [Male]       174       103
2     False      True      True
3      True      True      True

In [19]:
def get_best_split(y, data):
    '''
    Given a data, select the best split and return the variable, the value, the variable type and the IG.
    y: name of the target variable
    data: dataframe where to find the best split.
    '''
    masks = data.drop(y, axis= 1).apply(max_information_gain_split, y = data[y])
    if sum(masks.loc[3,:]) == 0:
        return(None, None, None, None)

    else:
        # Get only masks that can be splitted
        masks = masks.loc[:,masks.loc[3,:]]

        # Get the results for split with highest IG
        split_variable = max(masks)
        #split_valid = masks[split_variable][]
        split_value = masks[split_variable][1] 
        split_ig = masks[split_variable][0]
        split_numeric = masks[split_variable][2]

        return(split_variable, split_value, split_ig, split_numeric)


def make_split(variable, value, data, is_numeric):
    '''
    Given a data and a split conditions, do the split.
    variable: variable with which make the split.
    value: value of the variable to make the split.
    data: data to be splitted.
    is_numeric: boolean considering if the variable to be splitted is numeric or not.
    '''
    if is_numeric:
        data_1 = data[data[variable] < value]
        data_2 = data[(data[variable] < value) == False]

    else:
        data_1 = data[data[variable].isin(value)]
        data_2 = data[(data[variable].isin(value)) == False]

    return(data_1,data_2)

def make_prediction(data, target_factor):
    '''
    Given the target variable, make a prediction.
    data: pandas series for target variable
    target_factor: boolean considering if the variable is a factor or not
    '''

    # Make predictions
    if target_factor:
        pred = data.value_counts().idxmax()
    else:
        pred = data.mean()

    return pred

In [20]:
def train_tree(data,y, target_factor, max_depth = None,min_samples_split = None, 
               min_information_gain = 1e-20, counter=0, max_categories = 20):
    '''
    Trains a Decission Tree
    data: Data to be used to train the Decission Tree
    y: target variable column name
    target_factor: boolean to consider if target variable is factor or numeric.
    max_depth: maximum depth to stop splitting.
    min_samples_split: minimum number of observations to make a split.
    min_information_gain: minimum ig gain to consider a split to be valid.
    max_categories: maximum number of different values accepted for categorical values. High number of values will 
    slow down learning process. R
    '''

    # Check that max_categories is fulfilled
    if counter==0:
        types = data.dtypes
        check_columns = types[types == "object"].index
        for column in check_columns:
            var_length = len(data[column].value_counts()) 
            if var_length > max_categories:
                raise ValueError('The variable ' + column + ' has '+ str(var_length) + \
                                 ' unique values, which is more than the accepted ones: ' +  str(max_categories))

    # Check for depth conditions
    if max_depth == None:
        depth_cond = True

    else:
        if counter < max_depth:
            depth_cond = True

        else:
            depth_cond = False

    # Check for sample conditions
    if min_samples_split == None:
        sample_cond = True

    else:
        if data.shape[0] > min_samples_split:
            sample_cond = True

        else:
            sample_cond = False

    # Check for ig condition
    if depth_cond & sample_cond:

        var,val,ig,var_type = get_best_split(y, data)

        # If ig condition is fulfilled, make split 
        if ig is not None and ig >= min_information_gain:

            counter += 1

            left,right = make_split(var, val, data,var_type)

            # Instantiate sub-tree
            split_type = "<=" if var_type else "in"
            question =   "{} {}  {}".format(var,split_type,val)
            # question = "\n" + counter*" " + "|->" + var + " " + split_type + " " + str(val) 
            subtree = {question: []}

            # Find answers (recursion)
            yes_answer = train_tree(left,y, target_factor, max_depth,min_samples_split,min_information_gain, counter)
            no_answer = train_tree(right,y, target_factor, max_depth,min_samples_split,min_information_gain, counter)

            if yes_answer == no_answer:
                subtree = yes_answer

            else:
                subtree[question].append(yes_answer)
                subtree[question].append(no_answer)

        # If it doesn't match IG condition, make prediction
        else:
            pred = make_prediction(data[y],target_factor)
            return pred

    # Drop dataset if doesn't match depth or sample conditions
    else:
        pred = make_prediction(data[y],target_factor)
        return pred

    return subtree

max_depth = 5
min_samples_split = 20
min_information_gain  = 1e-5


decisiones = train_tree(data,'obese',True, max_depth, min_samples_split, min_information_gain)


decisiones

{'Weight <=  103': [{'Weight <=  74': [0,
    {'Weight <=  84': [{'Weight <=  75': [1, 0]},
      {'Weight <=  98': [1, 0]}]}]},
  1]}

In [21]:
def clasificar_datos(observacion, arbol):
    question = list(arbol.keys())[0] 

    if question.split()[1] == '<=':
        if observacion[question.split()[0]] <= float(question.split()[2]):
            answer = arbol[question][0]
        else:
            answer = arbol[question][1]

    else:
        if observacion[question.split()[0]] in (question.split()[2]):
            answer = arbol[question][0]
        else:
            answer = arbol[question][1]

    # If the answer is not a dictionary
    if not isinstance(answer, dict):
        return answer
    else:
        residual_tree = answer
    
    return clasificar_datos(observacion, answer)

In [23]:
print('Algorithm Accuracy:', accuracy)

NameError: name 'accuracy' is not defined